# Generated by Django 4.2.3 on 2023-07-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0002_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='breed',
            new_name='bread',
        ),
    ]
